### ISSUE TITLE
Slow cache transpilation

### ISSUE THREAD

**Issue by znk** [saltyshiomix/react-ssr#1]
Hello @saltyshiomix,
I toyed a bit with `react-ssr`, and find it very intuitive to play with. I see the potential for various professional projects. Only one feature that plays well nicely with HMR remains: proper cache invalidation.

As the number of dependencies (e.g: semantic-ui-react) and target files grows, compilation takes a longer time. Meanwhile, express has no file to serve and trows an error. Current cache strategy (erasing .ssr folder, transpiling everything on each file change) wont scale up.

How would you implement an incremental transpilation? Naive way would be through chokidar and transpile/updating the only the changed files. But I do feel there are pitfalls. I will take time to propose a PR that, and I would appreciate your input.

Serdar.

**Comment by saltyshiomix** [comment]
Hi @znk , thank you very much for your trying this project!

I totally agree with the incremental transpiration.

When the first implementation of `react-ssr`, there were no `.ssr` file output and I found compilation was so slow, and I tackled the problem by unioning `fs` and `memory-fs` for the faster compiletion.

```ts
const ufs = require('unionfs').ufs;
const MemoryFileSystem = require('memory-fs');
const memfs = new MemoryFileSystem();
ufs.use(fs).use(memfs);

const compiler: webpack.Compiler = webpack(configureWebpack(entry));
compiler.inputFileSystem = ufs;
compiler.run((err: Error) => {
    err && console.error(err.stack || err);
});
```

But if we can wait until the incremental compilation is ready, there are no need to have `.ssr` when development mode:

```ts
app.engine('tsx', renderFile);
app.set('views', path.join(process.cwd(), config.viewsDir));
app.set('view engine', 'tsx');

// currently override express' `app.listen()` to wait until "whole" compilation is ready
app.listen = function() {
  const args: any = arguments;
  const server = http.createServer(app);
  // this `optimize` function compiles scripts and registers script routes
  optimize(app, server).then((server) => {
    server.listen.apply(server, args);
  });
  return server;
};
```

I think it is possible to implement the incremental transpilation easily if we could register script routes:

- want to register routes like this **from memory fs**
  - `/index.js?props=?props= woTCo29uZQHCo3R3bwLCpXRocmVlwpMBAgPCpGZvdXLCrsSOZCBwacSDYXBwbGVz`
- my first thought
  - read results from `webpack-dev-middleware` like `webpack-dev-server`?
  - or read results from `webpack.compiler.watch()`?

PRs are of course welcome.

I'm very much looking forward!

Yoshihide.

**Comment by saltyshiomix** [comment]
@znk 

I added the incremental compilation feature by using `webpack-dev-server` since `react-ssr@^0.9`!

If you have any advices, please reopen this issue and send a PR anytime 👍

**Comment by znk** [comment]
It works nicely!! @saltyshiomix, it is way smarter to not reinvent the wheel as I would have done!
