### ISSUE TITLE
npm install @types/react

### ISSUE THREAD

**Issue by terary** [saltyshiomix/react-ssr#12]
I think the directions for 'With @react-ssr/nestjs-expres' 
is missing:
`npm install @types/react`
Excuse me if I am mistaking - but that little bit seemed necessary to i make views/index.tsx recognize react components

**Comment by saltyshiomix** [comment]
Hi, @terary !

Thank you for your issue.
Yes TypeScript users should install type definitions of React, but this is the knowledge of React so I don't mention it in the README.

If you don't want to install types, please set `strict: false` in the tsconfig.json :)
