### ISSUE TITLE
[Question]: Redux example.

### ISSUE THREAD

**Issue by ovidius72** [saltyshiomix/react-ssr#13]
Hi, do you have any example on how to send the state from the server to the client. Using redux for example, when you switch from a page to another, how do you manage the application state ?

**Comment by saltyshiomix** [comment]
@ovidius72 
Thank you for your question!

You mean page transitions (with url) by using Redux?

Currently react-ssr provides only view template engine feature, so it might be difficult to do that.

I'll try to use Redux later :)

**Comment by ovidius72** [comment]
I'm not referring to page transitions. I would like to send down the initial state when rendering on the server. Please, look at this example from the redux documentation https://redux.js.org/recipes/server-rendering/

They send down a json object attached to the window.__PRELOADED_STATE__ global variable.
Maybe there could be a way to do the same with the __document page ?
Anyway, since i've started playing around with react-ssr, i found that the initial state can also be send down as a Prop and then rebuilt in the client code.

However, it's a great job.

**Comment by ovidius72** [comment]
Hey @saltyshiomix I'm sorry to bother you again but I'm having a problem with hot reload. When i make some change the page is fully reloaded

![React_SSR_-__About__e_about_tsx____Projects_opa_tsnodessr_src_web-react_views__-_NVIM](https://user-images.githubusercontent.com/3592928/72685512-40f8e380-3aeb-11ea-9f8d-5a4f15eceea2.png)

I see this error in the console. Do you have any idea ? I guess it is something to do with webpack-dev-server.

**Comment by saltyshiomix** [comment]
@ovidius72 

I tested:

- create a new file for the client
  - import it in `views/index.tsx`
  - update it
- create a new CSS for the client
  - import it in `views/index.tsx`
  - update it

But no errors found.

If you get this error everytime, could you tell me more information with an example repository?

**Comment by ovidius72** [comment]
Thanks @saltyshiomix 
Can you try using typescript ?
It seems that when something changes in the index.tsx page the server is also restarted causing the page to refresh.
I'll try to put online an example later.

**Comment by saltyshiomix** [comment]
Thank you, @ovidius72 

But I'm already using TypeScript.

Anyway, I think react-ssr is not compatible or suitable for React Redux structures.

For example, let's see if we implemented `views/todo.tsx` like this:

```tsx
interface IndexPageProps {
  todos: TodoState[];
}

const IndexPage = (props: IndexPageProps) => {
  const { todos } = props; // passed from the server

  const initialState = {
    todo: {
      todos,
    }
  };

  return (
    <Provider store={createStore(rootReducer, initialState)}>
      <h1>Todo List</h1>
      <AddTodo />
      <Todos />
    </Provider>
  );
};

export default IndexPage;
```

It's not impossible to implement, but in this case the code below is smarter than the above?

```tsx
interface IndexPageProps {
  todos: TodoState[];
}

const IndexPage = (props: IndexPageProps) => {
  const { todos } = props; // passed from the server

  return (
    <React.Fragment>
      <h1>Todo List</h1>
      <AddTodo />
      <Todos todos={todos} />
    </React.Fragment>
  );
};

export default IndexPage;
```

**Comment by saltyshiomix** [comment]
@ovidius72 

I'll try to add `views/_app.(js|ts)x` to tackle this issue :)

**Comment by ovidius72** [comment]
@saltyshiomix Thanks and sorry for the lacking of my responses but I've had no time in the last few days to test the issue again. I will do more tests during the next week hopefully.

**Comment by saltyshiomix** [comment]
@ovidius72 

Thank you for your reply :)

No problem, I was bussy at work, too.

I want to add this feature in the next minor release. I'll implement and test it next few weeks :)

**Comment by saltyshiomix** [comment]
@ovidius72 

Sorry for late reply.

I implemented [examples/with-tsx-redux-todo](https://github.com/saltyshiomix/react-ssr/tree/master/examples/with-tsx-redux-todo).

If you have time, please try it :)

**views/index.tsx**

```tsx
interface IndexPageProps {
  todos: Todo[];
};

const IndexPage = (props: IndexPageProps) => {
  // use server data as preloaded state
  const preloadedState = {
    todos: props.todos,
  };

  const store = createStore(rootReducer, preloadedState);

  return (
    <Provider store={store}>
      <AddTodo />
      <TodoList />
    </Provider>
  );
};

export default IndexPage;
```

**Comment by saltyshiomix** [comment]
@ovidius72 
If any updates, feel free to reopen the issue :)
