### ISSUE TITLE
rollup-plugin-terser - makes the distribution difficult to read and debug

### ISSUE THREAD

**Issue by brendonjohn** [saltyshiomix/react-ssr#16]
Hey salty 💚 ,

I'm currently debugging an issue I'm having with react-ssr and have been looking in the @react-ssr/core source code.

I see that the distribution is currently minified by `rollup-plugin-terser`, which makes the published version incomprehensible.

What do you think of removing the terser step? I'm happy to raise the PR for this.

In the meantime, I'll make do by linking npm modules locally.

**Comment by saltyshiomix** [comment]
Hi @brendonjohn , sorry for late reply.

I think it's better to separate dev and prod like `react`:

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

https://github.com/facebook/react/blob/master/packages/react/npm/index.js

If you like this, I'll do this this or next week :)
