### ISSUE TITLE
No server-side HMR

### ISSUE THREAD

**Issue by znk** [saltyshiomix/react-ssr#2]
Hello @saltyshiomix, 
For any project from `examples` folder using `react-ssr@latest` in development mode, that nice server-side hot reload module seem not functioning anymore: any change on the server file and update on an API endpoint doesn't result of being taken in account, only the client-side does.

Can you leave me this one to investigate?

**Comment by saltyshiomix** [comment]
Yes yes, please go ahead, @znk !

Thank you so much for reporting the issue!

**Comment by saltyshiomix** [comment]
@znk 

Server side reloading is formally implemented by using `reload`.

But I think that possibly it is the better solution by using nodemon.

I'm looking forward your advices!

**Comment by e0** [comment]
I can add that I'm using nodemon and it seems to work fine. [This article](https://medium.com/create-a-server-with-nodemon-express-typescript/create-a-server-with-nodemon-express-typescript-f7c88fb5ee71) helped a lot.

**Comment by saltyshiomix** [comment]
@znk 

How do you think of manually using nodemon?

I think it is difficult to track all server files, so it may be better to leave the users to setting up nodemon.

**Comment by znk** [comment]
@saltyshiomix : nodemon does a wonderful job. I personally dont appreciate how bloated it is. At work, I maintain a fork of [supervisor](https://github.com/petruisfan/node-supervisor/) and bootstrap express server to be launched programmatically.

**Comment by saltyshiomix** [comment]
@znk 

Sorry, I'm not so familiar with English.

Please let me know how to tackle this issue?

**Comment by saltyshiomix** [comment]
If any troubles or advices, feel free to reopen the issue 👍

**Comment by malixsys** [comment]
```
"dev": "ts-node-dev --respawn --transpileOnly --project server/tsconfig.json server/main.ts",
```
