### ISSUE TITLE
Styled component ThemeProvider

### ISSUE THREAD

**Issue by Krakof** [saltyshiomix/react-ssr#20]
Hi,
I'm getting some theme props from backend and want to pass them to ThemeProvider

**controller.ts**
```
@Get('/:id/some-url')
  @Header('content-type', 'text/html')
  @Render('myComponent')
  async myMethod() {
   //here I'm getting props from DB
  return {
  // props for my component
 }
}
```

**myComponent.tsx**
```
const Component: React.FC = (props) => {
  console.log(props); // everything OK here
  return (
      <ThemeProvider theme={props.theme}>
          <React.Fragment>
              <GlobalStyle />
                  <Header> // global styles aren't applying here
                    <BackButton />
                  </Header>
            </React.Fragment>
      </ThemeProvider>
  );
};

export default Component;
```

Could you please help me with this issue?
Thanks in advance

**Comment by saltyshiomix** [comment]
Hi @Krakof 

I'll investigate this this week, please wait a moment!

**Comment by Krakof** [comment]
Sure @saltyshiomix , thanks a lot for the quick answer. Just FYI I'm using @react-ssr/nestjs-express

**Comment by bukhalo** [comment]
@saltyshiomix Also, сan you make an example of how to use `createGlobalStyle` from `styled-components` package?

**Comment by Krakof** [comment]
@saltyshiomix Sorry, that was my fault. I've missed ssr.config.js
@bukhalo Just the same way as styled-component [docs](https://styled-components.com/docs/api) createGlobalStyle. Do not forget about ssr.config.js

**Comment by saltyshiomix** [comment]
@Krakof 
No problem! It worked?

**Comment by saltyshiomix** [comment]
And v0.21.3 is out, `views/_app` support added :)
