### ISSUE TITLE
response.render('home', { message }) return empty object;

### ISSUE THREAD

**Issue by elfexor** [saltyshiomix/react-ssr#22]
module.exports = {
  viewsDir: 'src/views'  **// if views in subdirectory** 
};

if views folder in subdirectory, response.render() returnes empty object.

app.get('/', (request: Request, response: Response) => {
        const message = 'Hello World!';
        response.render('home', { message }); // returned -> {}
    });

**Comment by saltyshiomix** [comment]
Hi @elfexor , thank you for your reporting the issue.

I tested it, but I can't reproduce it.
Could you tell me more information? (like directory structures)

Best,

**Comment by saltyshiomix** [comment]
@elfexor 

I also tested it on Windows 10, but it workd.

**Comment by elfexor** [comment]
When installed from the examples, it worked. The problem was on my side. I'm sorry to trouble you.

**Comment by saltyshiomix** [comment]
@elfexor 
No problem. Feel free to open issues :)
