### ISSUE TITLE
Webpack config.optimization.splitChunks.chunks = "all"

### ISSUE THREAD

**Issue by Marcus-Rise** [saltyshiomix/react-ssr#27]
Is it possible to use set webpack config split all chunks in `ssr.config.js`?  

```js
// ssr.config.js
...
webpack: (config, env) => {
        if (env === "production") {
            config.optimization.splitChunks.chunks = "all";

...
```

**Comment by Marcus-Rise** [comment]
Any help?

**Comment by mabdu11ah** [comment]
Ive tried this and it does reduce js file size radically, but my css is now blank and doesn't load.

**Comment by adelsagemilang** [comment]
> Any help?

Have the same issue here, any update on this?

**Comment by Marcus-Rise** [comment]
Walking around this issue I decided that [this package](https://github.com/kyle-mccarthy/nest-next), which works with [Nextjs](https://nextjs.org/) will be good solusition for my projects
