### ISSUE TITLE
When will antd support be available?

### ISSUE THREAD

**Issue by YikSanChan** [saltyshiomix/react-ssr#3]

**Comment by saltyshiomix** [comment]
Hi @YikSanChan !

Sorry for the inconvenience.
I'll add support for antd later today!

**Comment by YikSanChan** [comment]
@saltyshiomix Impressive, look forward to it!

**Comment by saltyshiomix** [comment]
@YikSanChan 

Currently I'm rewriting whole codes, so antd support will be in the few days, sorry.

This drastically rewrites will make react-ssr more performant!

**Comment by YikSanChan** [comment]
No worry, thanks for your work!

Shiono Yoshihide <notifications@github.com>于2019年11月10日 周日下午11:31写道：

**Comment by saltyshiomix** [comment]
We will support antd after fixing #4 and #6 :)

**Comment by saltyshiomix** [comment]
#4 is fixed, and #6 will be soon.

React hydration is successfully with antd in my testing repo 👍 

Please wait a moment :)

**Comment by saltyshiomix** [comment]
@YikSanChan 

Support antd as of `v0.11.17` 👍 

Please check out [examples/with-jsx-antd](https://github.com/saltyshiomix/react-ssr/tree/master/examples/with-jsx-antd) :)

**Comment by YikSanChan** [comment]
@saltyshiomix awesome! I will check tonight and let you know if it works on my end. Thx!

**Comment by YikSanChan** [comment]
It works :) thx for your help
