### ISSUE TITLE
Using links in dynamic Head 

### ISSUE THREAD

**Issue by e0** [saltyshiomix/react-ssr#5]
It looks like it is currently not possible to use the `link` tag inside the `Head` component. Looking through the code, I think it could be made extending this [switch statement](https://github.com/saltyshiomix/react-ssr/blob/ec108e8e80294f6fbfd519a52bca1329b7ba5d48/packages/core/src/components/Head/index.tsx#L62). Do you think this is the right approach? Please let me know if it is and if you want me to help work on this.

P.S. This project looks really impressive and I appreciate your dedication on writing something that provides such good developer experience. Thank you!

**Comment by saltyshiomix** [comment]
Best words to me, thank you so much @e0 !

I think this is a bug of [this function](https://github.com/saltyshiomix/react-ssr/blob/master/packages/core/src/render/stringify/helpers.ts#L11) which generates server side html.

It ignores all head tags except meta and title.

While investigating, I found the solution so I released patch version just now.

Could you check `v0.11.5`?

**Comment by saltyshiomix** [comment]
@e0 

If you are interested in sending PR, just open PR without issues :)

(Please write why and what in your PR, I think this is enough to current major version (v0).)

**Comment by e0** [comment]
I tried it out and it seems to work great now. Looks like I was looking at the wrong place. Thank you so much for the quick fix!

**Comment by saltyshiomix** [comment]
If any other troubles, feel free to reopen the issu 👍
