### ISSUE TITLE
Problem with importing css in custom layout

### ISSUE THREAD

**Issue by e0** [saltyshiomix/react-ssr#6]
I think I noticed a problem where css files are not being loaded properly in `_document.[jsx/tsx]`. To replicate this, you can add the following `views/_document.jsx` to the [basic-css example](https://github.com/saltyshiomix/react-ssr/tree/master/examples/basic-css).

```jsx
import React from 'react';
import { Document, Head, Main } from '@react-ssr/express';
import '../styles/index.css';

export default class extends Document {
  render() {
    return (
      <html lang="en">
        <Head>
          <title>An example of @react-ssr/express</title>
        </Head>
        <body>
          <Main />
        </body>
      </html>
    );
  }
}
```

and remove the following line from `views/index.jsx` file.

```jsx
import '../styles/index.css';
```

If it helps, the stylesheet seems to load properly if the layout is manually imported. So adding the following line in `views/index.jsx` "works".

```jsx
import './_document';
```

I wouldn't mind trying to tackle this problem but wanted to see if you have any pointers or ideas on where to start looking. Thank you!

**Comment by saltyshiomix** [comment]
@e0 

Thank you for your reporting the issue!

I'll investigate it in the next few days 👍

**Comment by saltyshiomix** [comment]
@e0 

Bit thanks to your detailed explanation!

I finally got it that the server compiles whole document but extract no css, sorry.

On the other hand, `index.jsx` entry will be hydrated in `id=react-ssr-root`, so after hydration we will see the views with css.

Could you send PR with tackling following points?

#### Step 1

- clone react-ssr.

#### Step 2

- create your testing repo
- create `package.json` like this:

```json
{
  "dependencies": {
    "@react-ssr/core": "/absolute/path/to/your/react-ssr/core",
    "@react-ssr/express": "/absolute/path/to/your/react-ssr/express"
  }
}
```

`@react-ssr/express` depends on `@react-ssr/core`, so we must specify the core package on development.

- fix `react-ssr`, and reinstall example repo.
- test it, that's it!

#### Step 3

I want to fix this issue by tackling these points:

##### Extract CSS with the same naming with JS

See [webpack.config.ts](https://github.com/saltyshiomix/react-ssr/blob/master/packages/core/src/optimize/webpack.config.ts) and [helper.ts](https://github.com/saltyshiomix/react-ssr/blob/master/packages/core/src/optimize/helpers.ts), and it may be the solution by using [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) or so.

##### Create CSS entry point like `script`

See [here](https://github.com/saltyshiomix/react-ssr/blob/master/packages/core/src/render/stringify/default.tsx#L24) for more details.

##### Create CSS routes

See [here](https://github.com/saltyshiomix/react-ssr/blob/master/packages/core/src/optimize/development.ts#L54) and [here](https://github.com/saltyshiomix/react-ssr/blob/master/packages/core/src/optimize/production.ts).

Or any advices are welcome.

I'm looking forward to your PR :)

**Comment by saltyshiomix** [comment]
In the future, we want to split chunks properly.

For now (`v0`), it will be good with single entry point each asset :)

**Comment by e0** [comment]
@saltyshiomix thank you for the detailed guide! I will try to see if I can fix it.

**Comment by saltyshiomix** [comment]
@e0 

I just published `v0.11.10`, so please use latest master branch to work on it :)

For a while I'll improve examples so you can take time to tackle the issue 👍

**Comment by saltyshiomix** [comment]
@e0 

I found the lack of the guide above.

Please wait to send PR until creating CONTRIBUTION.md, sorry.

I fixed the issue as of `v0.11.16`.

Please check out your sample repo :)

**Comment by e0** [comment]
@saltyshiomix Thank you for the update. I tried working on it during the weekend but didn't get very far. It's really educational to see how you extract the css in [this commit](https://github.com/saltyshiomix/react-ssr/commit/b7c100cb6fea9df33f5e425a849f6d0449585abf).

I think I didn't explain the problem well the first time though. The specific problem I had was with the importing css from the `_document.jsx` file. I forked this repo and added a [commit](https://github.com/e0/react-ssr/commit/3915a6d34a16f5b9cb784b859c039b9cb5711acb) to demonstrate the problem. Please let me know if I'm missing anything or if you want any other information.

**Comment by saltyshiomix** [comment]
@e0 

Sorry you are right and I made a mistake.

Your fork repo is perfectly right and this issue should be reopen.

**Comment by saltyshiomix** [comment]
@e0 

I finally got it:

- `_document` will be `ReactDOMServer.renderToString`, so import styles or scripts are ignored
- other views are hydrated to `id=react-ssr-root` DOM, so import styles or scripts are reflected

And `react-ssr` is aim to view template engine, so we can and should use global styles or scripts by using `app.use(express.static('public'))` 👍 

If any troubles or advices, feel free to reopen the issue 👍

**Comment by saltyshiomix** [comment]
And what I want to say as mentioned [this comment](https://github.com/saltyshiomix/react-ssr/issues/6#issuecomment-555217880), I'll explain later with `CONTRIBUTION.md`.

**Comment by e0** [comment]
@saltyshiomix I think it's a good solution and design choice. Thank you the update!
