### ISSUE TITLE
What effort is needed to bring in a new lib?

### ISSUE THREAD

**Issue by YikSanChan** [saltyshiomix/react-ssr#7]
I want to server-side render QRCode with https://github.com/zpao/qrcode.react however it is not yet supported. I am curious how much work is needed to enable this.

**Comment by e0** [comment]
I just want to chime in and add that this seems like a very general and specific question at the same time. In general, many libraries should work out of the box and of course it depends a lot on the implementation of every library.

More specifically, I have actually been using another qrcode library (https://github.com/soldair/node-qrcode) with react-ssr and they work great alongside each other. It is not react specific but it is trivial to make a simple react component with it. I did it like this using functional components:

```javascript
const QrCode = ({dataUrl}) =>
  dataUrl.length > 0 ? <img src={dataUrl} /> : <></>;
```

then you can populate the url like this:

```javascript
...
    
const [dataUrl, setDataUrl] = useState("");

...

QRCode.toDataURL(myUrl, (err, url) => {
  setDataUrl(url);
});

...

<QrCode dataUrl={dataUrl} />

...
```

**Comment by YikSanChan** [comment]
@e0 QRCode.toDataURL is an async call, do you put it inside an `useEffect`?

**Comment by e0** [comment]
Yes exactly, I have a small helper file to support both client and server side rendering that looks like this:

```javascript
import {useLayoutEffect, useEffect} from "react";

const useIsomorphicLayoutEffect =
  typeof window !== "undefined" ? useLayoutEffect : useEffect;

export default useIsomorphicLayoutEffect;
```

then use it like:

```javascript
useIsomorphicLayoutEffect(() => myWrapperFunctionAroundToDataUrl(), []);
```

**Comment by YikSanChan** [comment]
I find out I can actually use `qrcode.react` with the lib

**Comment by saltyshiomix** [comment]
@e0 

Thank you very much!

@YikSanChan 

Feel free to open issues like this 👍
