### ISSUE TITLE
html rendered from react component loses styles after passing back to the client

### ISSUE THREAD

**Issue by YikSanChan** [saltyshiomix/react-ssr#8]
My use case for the lib is to:
- render react component on server side into html
- pass the html back to client side
- client side (a web app) prints the html using [expo-print](https://docs.expo.io/versions/latest/sdk/print/)

I am testing with jsx-with-antd. On server side it shows
![image](https://user-images.githubusercontent.com/17229109/69763344-bcf53180-1121-11ea-9dc3-bf8034ddce24.png)
But on client side print preview I get
![image](https://user-images.githubusercontent.com/17229109/69763269-828b9480-1121-11ea-964a-1e8e0ebd88f7.png)

It seems all styles get lost. Is it due to on client side I am not able to get _react-ssr?

**Comment by saltyshiomix** [comment]
@YikSanChan 

Printing is much more difficult, I'll try expo-print later.

We can't use all styles to print.

Do you know paper-css?

https://github.com/cognitom/paper-css

It may help you, I think :)

**Comment by saltyshiomix** [comment]
@YikSanChan 

If any updates, feel free to reopen the issue 👍
