### ISSUE TITLE
Removing unwanted html comments from Rehydrate

### ISSUE THREAD

**Issue by stevenanthonyrevo** [saltyshiomix/react-ssr#9]
The output of "Main" component from "@react-ssr/express" creates unnecessary HTML comments in the markup - example of the output: `<!-- -->` from within the generated server-side source. 

A fix would be including a regex to remove any uncommented html tags. 
`.replace(/<!--(.*?)-->/g, '')`

Any help would be great on this, as I rather my markup be clear of comment tags.

**Comment by saltyshiomix** [comment]
@stevenanthonyrevo 

Hi, thank you for your question.

It is necessary for React to hydrate DOM properly.

If you are interesting, [see the documentation of ReactDOMServer#renderToString()](https://reactjs.org/docs/react-dom-server.html#rendertostring).
